server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

spring:
  application:
    name: gateway-service

zuul:
  routes:
    rest-service:
      path: /api/**
      url: http://localhost:8072/
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      strip-prefix: false
      sensitive-headers: Cookie, Set-Cookie


instance:
    hostname: localhost
